packageExtensions:
  "@npmcli/metavuln-calculator@*":
    dependencies:
      json-parse-even-better-errors: "*"
  bin-links@*:
    dependencies:
      mkdirp-infer-owner: "*"
  skypack@*:
    dependencies:
      tar: "*"
  snowpack@*:
    dependencies:
      magic-string: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.js
